# Generated by Django 5.0.9 on 2026-09-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("job_board", "Job Board"),
                            ("referral", "Referral"),
                            ("career_site", "Career Site"),
                            ("agency", "Agency"),
                        ],
                        default="career_site",
                        max_length=20,
                    ),
                ),
                ("resume_text", models.TextField()),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
